docker:
  repo: manu343726
  name: tinyrefl

stages:
  - clang-format-check
  - test
  - user-integration
  - conan-integration

clang-format-check:
  tags:
    - linux
    - docker
  image: saschpe/clang
  script:
    - apk update && apk add bash git
    - /bin/bash ./ci/ci_clang_format_check.sh
    - echo clang-format was applied ok
  config:
    - allow_failure: true

test:
  tags:
    - linux
    - docker
  toolchains:
    - clang50-x86
    - clang60-x86
    - clang70-x86
    - clang80-x86
    - clang90-x86
    - clang100-x86
    - gcc5-armv7
    - gcc5-x86
    - gcc6-armv7
    - gcc6-x86
    - gcc7-armv7
    - gcc7-x86
    - gcc8-armv7
    - gcc8-x86
    - gcc9-armv7
    - gcc9-x86
    - gcc10-armv7
    - gcc10-x86
  llvm-versions:
    - 4.0.0
    - 5.0.0
    - 6.0.0
  script:
    - ./ci/ci_test.sh
    - echo finished ok

user-integration:
  tags:
    - linux
    - docker
  toolchains:
    - clang50-x86
    - clang60-x86
    - clang70-x86
    - clang80-x86
    - clang90-x86
    - clang100-x86
    - gcc5-armv7
    - gcc5-x86
    - gcc6-armv7
    - gcc6-x86
    - gcc7-armv7
    - gcc7-x86
    - gcc8-armv7
    - gcc8-x86
    - gcc9-armv7
    - gcc9-x86
    - gcc10-armv7
    - gcc10-x86
  llvm-versions:
    - 4.0.0
    - 5.0.0
    - 6.0.0
  script:
    - ./ci/ci_user_integration.sh
    - echo finished ok

conan-integration:
  tags:
    - linux
    - docker
  toolchains:
    - clang50-x86
    - clang60-x86
    - clang70-x86
    - clang80-x86
    - clang90-x86
    - clang100-x86
    - gcc5-armv7
    - gcc5-x86
    - gcc6-armv7
    - gcc6-x86
    - gcc7-armv7
    - gcc7-x86
    - gcc8-armv7
    - gcc8-x86
    - gcc9-armv7
    - gcc9-x86
    - gcc10-armv7
    - gcc10-x86
  llvm-versions:
    - 4.0.0
    - 5.0.0
    - 6.0.0
  script:
    - ./ci/ci_conan_integration.sh
    - echo finished ok
