#ifndef TINYREFL_UTILS_PREPROCESSOR_HPP_INCLUDED
#define TINYREFL_UTILS_PREPROCESSOR_HPP_INCLUDED

#ifndef TINYREFL_PP_CAT
#define TINYREFL_PP_CAT_IMPL(x, y) x##y
#define TINYREFL_PP_CAT(x, y) TINYREFL_PP_CAT_IMPL(x, y)
#endif // TINYREFL_PP_CAT

#ifndef TINYREFL_PP_STR
#define TINYREFL_PP_STR(...) #__VA_ARGS__
#endif // TINYREFL_PP_STR

#ifndef TINYREFL_PP_UNWRAP
#define TINYREFL_PP_UNWRAP(...) __VA_ARGS__
#endif // TINYREFL_PP_UNWRAP

#endif // TINYREFL_UTILS_PREPROCESSOR_HPP_INCLUDED
